### ISSUE TITLE
Bug: crash with `BorrrowMutError` for aiofile.TextFileWrapper

### ISSUE THREAD

**Issue by mokurin000** [mtshiba/pylyzer#106]
```text
thread 'run' panicked at C:\Users\neko_poly000\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\erg_compiler-0.6.45\ty\typaram.rs:1659:24:
Forkable::borrow_mut: BorrowMutError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'run' panicked at C:\Users\neko_poly000\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\erg_compiler-0.6.45\ty\free.rs:1154:37:
Forkable::borrow_mut: BorrowMutError
```

env:
windows 11
Python 3.11.9 (micromamba python as system intepreter)

version: 0.0.63

minimum repreduce:

```python
from aiofile import TextFileWrapper
```

**Comment by mtshiba** [comment]
Fixed in v0.0.66.
