### ISSUE TITLE
thread 'run' panicked - "byte index 17 is not a char boundary"

### ISSUE THREAD

**Issue by sahuagin** [mtshiba/pylyzer#120]
**Describe the bug**
Using pylyzer in helix editor.
when opening a test file in project language server restarts due to pylyzer panicking.

**Reproducible Code**

Common includes that can be shared:

```python
import datetime as dt
import logging
import lzma
import os
import regex
import shutil
from pathlib import Path, PosixPath
from tempfile import TemporaryDirectory

import polars as pl
from polars.testing import assert_frame_equal
import pytest
```
The above has nothing to do with the error however, when pylyzer starts to examine every file it comes across these files and has the error.

Searching for the line indicated that caused issues:

```console
 ➜  rg '# Copyright 2016–2021 Julien Danjou' ~/.local/lib/python3.12
/home/tcovert/.local/lib/python3.12/site-packages/pip/_vendor/tenacity/wait.py
1:# Copyright 2016–2021 Julien Danjou

/home/tcovert/.local/lib/python3.12/site-packages/pip/_vendor/tenacity/retry.py
1:# Copyright 2016–2021 Julien Danjou

/home/tcovert/.local/lib/python3.12/site-packages/pip/_vendor/tenacity/stop.py
1:# Copyright 2016–2021 Julien Danjou
 
```

**Expected behavior**
No panic.

**Screenshots**
```
2024-12-30T11:06:45.826 helix_lsp::transport [ERROR] pylyzer err <- "thread 'run' panicked at /home/runner/.cargo/git/checkouts/parser-aad50aa3362d3a85/5e9d985/vendored/src/source_location/line_index.rs:114:28:\n"
2024-12-30T11:06:45.826 helix_lsp::transport [ERROR] pylyzer err <- "byte index 17 is not a char boundary; it is inside '–' (bytes 16..19) of `# Copyright 2016–2021 Julien Danjou\n"
2024-12-30T11:06:45.826 helix_lsp::transport [ERROR] pylyzer err <- "# Copyright 2016 Joshua Harlow\n"
2024-12-30T11:06:45.826 helix_lsp::transport [ERROR] pylyzer err <- "# Copyright 2013-2014 Ray Holder\n"
2024-12-30T11:06:45.826 helix_lsp::transport [ERROR] pylyzer err <- "#\n"
2024-12-30T11:06:45.826 helix_lsp::transport [ERROR] pylyzer err <- "# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
2024-12-30T11:06:45.826 helix_lsp::transport [ERROR] pylyzer err <- "# you may not use this file except in compliance with the License.\n"
2024-12-30T11:06:45.826 helix_lsp::transport [ERROR] pylyzer err <- "# You may obtain a `[...]\n"
2024-12-30T11:06:45.826 helix_lsp::transport [ERROR] pylyzer err <- "note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
2024-12-30T11:07:17.883 helix_lsp::transport [ERROR] pylyzer err <- "thread 'run' panicked at /home/runner/.cargo/git/checkouts/parser-aad50aa3362d3a85/5e9d985/vendored/src/source_location/line_index.rs:114:28:\n"
2024-12-30T11:07:17.883 helix_lsp::transport [ERROR] pylyzer err <- "byte index 17 is not a char boundary; it is inside '–' (bytes 16..19) of `# Copyright 2016–2021 Julien Danjou\n"
2024-12-30T11:07:17.883 helix_lsp::transport [ERROR] pylyzer err <- "# Copyright 2016 Joshua Harlow\n"
2024-12-30T11:07:17.883 helix_lsp::transport [ERROR] pylyzer err <- "# Copyright 2013-2014 Ray Holder\n"
2024-12-30T11:07:17.883 helix_lsp::transport [ERROR] pylyzer err <- "#\n"
2024-12-30T11:07:17.883 helix_lsp::transport [ERROR] pylyzer err <- "# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
2024-12-30T11:07:17.883 helix_lsp::transport [ERROR] pylyzer err <- "# you may not use this file except in compliance with the License.\n"
2024-12-30T11:07:17.883 helix_lsp::transport [ERROR] pylyzer err <- "# You may obtain a `[...]\n"
```.

**Environment**
 - OS
 linux. debian12
 - Version
 
```console
 ➜  pylyzer --version
pylyzer 0.0.76
 
```

**Additional context**
Just upgraded and noticed the issue. Don't remember what version was upgraded from.

**Comment by jamesETsmith** [comment]
I'm seeing the same error on Ubuntu 22.04. For reference, I installed with `pip`.

**Comment by Mach1212** [comment]
I have the same issue in pylyzer 0.0.82
