### ISSUE TITLE
[Bug] Server fails with "No such file or directory" on startup

### ISSUE THREAD

**Issue by whateverforever** [mtshiba/pylyzer#16]
Hi, thank you for this nice project. I'd love to ditch pylance, as it's a memory and cpu hog. However starting the server fails for me on Ubuntu 20.10.

**Edit:** I just noticed you mention this in the readme, however this should not happen either way. At least not this cryptically

```bash
$ RUST_BACKTRACE=full pylyzer --server
thread 'main' panicked at 'ERG_PATH not found: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/shiba/.cargo/registry/src/github.com-1ecc6299db9ec823/erg_common-0.6.10-nightly.0/env.rs:10:10
stack backtrace:
   0:     0x55ca2e393a0a - std::backtrace_rs::backtrace::libunwind::trace::h595f06c70adcc478
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ca2e393a0a - std::backtrace_rs::backtrace::trace_unsynchronized::h177a0149c76cdde9
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ca2e393a0a - std::sys_common::backtrace::_print_fmt::hc0701fd2c3530c58
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55ca2e393a0a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4cd115d8750fd6c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55ca2e3b7e7e - core::fmt::write::h93e2f5923c7eca08
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
   5:     0x55ca2e390165 - std::io::Write::write_fmt::h8162dbb45f0b9e62
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
   6:     0x55ca2e3937d5 - std::sys_common::backtrace::_print::h1835ef8a8f9066da
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55ca2e3937d5 - std::sys_common::backtrace::print::hcb5e6388b9235f41
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55ca2e394fbf - std::panicking::default_hook::{{closure}}::h9c084969ccf9a722
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
   9:     0x55ca2e394cfb - std::panicking::default_hook::h68fa2ba3c3c6c12f
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:286:9
  10:     0x55ca2e3956c9 - std::panicking::rust_panic_with_hook::h8d5c434518ef298c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:688:13
  11:     0x55ca2e395469 - std::panicking::begin_panic_handler::{{closure}}::hf33414f5dabf6faf
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:579:13
  12:     0x55ca2e393ebc - std::sys_common::backtrace::__rust_end_short_backtrace::hc50389427413bb75
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55ca2e395172 - rust_begin_unwind
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
  14:     0x55ca2d6510e3 - core::panicking::panic_fmt::h2de7a7938f816de8
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
  15:     0x55ca2d651593 - core::result::unwrap_failed::hdc73d4affce1d414
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1790:5
  16:     0x55ca2e36be90 - erg_common::env::_erg_path::h7c41c06ca9e5d471
  17:     0x55ca2e3706b2 - std::thread::local::fast::Key<T>::try_initialize::h4299a168d7d6c295
  18:     0x55ca2e36c56b - erg_common::env::erg_path::hfa6affc8237ac118
  19:     0x55ca2d6f0fdb - els::server::Server<Checker>::new::hbc66c4a0ce7a9149
  20:     0x55ca2d6bb6ff - pylyzer::run::hee0ea689a38a6591
  21:     0x55ca2d6bca23 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf6761b5953500095
  22:     0x55ca2d77f709 - std::rt::lang_start::{{closure}}::h4fb14a749e265ed4
  23:     0x55ca2e38b3ac - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h699977d052768608
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:287:13
  24:     0x55ca2e38b3ac - std::panicking::try::do_call::h4e121e623c70f903
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  25:     0x55ca2e38b3ac - std::panicking::try::hf9d919e062bc178a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  26:     0x55ca2e38b3ac - std::panic::catch_unwind::h7a7b12272684cb97
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  27:     0x55ca2e38b3ac - std::rt::lang_start_internal::{{closure}}::hd96b0eb4844b8762
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:148:48
  28:     0x55ca2e38b3ac - std::panicking::try::do_call::h1af1f88f4f92a22c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  29:     0x55ca2e38b3ac - std::panicking::try::hf20d7abea7f0f097
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  30:     0x55ca2e38b3ac - std::panic::catch_unwind::hb0e084c3a9c042e4
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  31:     0x55ca2e38b3ac - std::rt::lang_start_internal::hca9d5c7277f5b67c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:148:20
  32:     0x55ca2d6bb865 - main
  33:     0x7f0a6b82c083 - __libc_start_main
                               at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  34:     0x55ca2d65177e - _start
  35:                0x0 - <unknown>
```

Installed using pip

```bash
$ python3 -m pip install pylyzer
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting pylyzer
  Downloading pylyzer-0.0.17-py3-none-manylinux_2_31_x86_64.whl (7.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 1.8 MB/s eta 0:00:00
Installing collected packages: pylyzer
Successfully installed pylyzer-0.0.17
```

System:

```
Linux <hostname> 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mtshiba** [comment]
You need to [install Erg](https://github.com/mtshiba/ergup) and set the environment variable `$ERG_PATH`.
