### ISSUE TITLE
[Error] Server failed with "No such file or directory"

### ISSUE THREAD

**Issue by BlueDruddigon** [mtshiba/pylyzer#19]
Hi, I'm currently using pylyzer installed with cargo integrated with neovim's lsp.
The language server return me this error

```
[ERROR][2023-04-23 15:23:48] .../vim/lsp/rpc.lua:734	"rpc"	"pylyzer"	"stderr"	"thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/els-0.1.23-nightly.2/file_cache.rs:170:10\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

Could you please help me with this ?

Regardless,
BlueD

**Comment by kobzar** [comment]
The same issue
```
[ERROR][2023-04-23 20:21:14] .../vim/lsp/rpc.lua:734	"rpc"	"pylyzer"	"stderr"	"thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }', /home/kobzar/.cargo/registry/src/github.com-1ecc6299db9ec823/els-0.1.23-nightly.0/file_cache.rs:161:62\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

**Comment by mtshiba** [comment]
Fixed with https://github.com/erg-lang/erg/commit/321c83cb11c180ffa2356e6335eb8ddec9e42e11.
