### ISSUE TITLE
Crash on parsing call statement

### ISSUE THREAD

**Issue by wookayin** [mtshiba/pylyzer#56]
pylyzer 0.0.47

I used this file: https://github.com/python/cpython/blob/3.10/Lib/test/test_grammar.py

```
RUST_BACKTRACE=1 pylyzer grammar_py310.py

thread 'pylyzer' panicked at 'called `Option::unwrap()` on a `None` value', /Users/wookayin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/py2erg-0.0.47/convert.rs:1057:40
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: py2erg::convert::ASTConverter::convert_expr::{{closure}}
   4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   5: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   6: py2erg::convert::ASTConverter::convert_expr
   7: py2erg::convert::ASTConverter::convert_statement
   8: py2erg::convert::ASTConverter::convert_block
   9: py2erg::convert::ASTConverter::convert_statement
  10: py2erg::convert::ASTConverter::convert_statement
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  12: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  13: py2erg::convert::ASTConverter::convert_program
  14: pylyzer::analyze::PythonAnalyzer::analyze
  15: pylyzer::analyze::PythonAnalyzer::run
  16: pylyzer::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Thread panicked: Any { .. }
```

L1057: https://github.com/mtshiba/pylyzer/blob/main/crates/py2erg/convert.rs#L1057

**Comment by foofaev** [comment]
Got same issue

**Comment by foofaev** [comment]
Here is a minimal reproducible example:
```py
class Foo:
    def __init__(self, bar, baz):
        self.bar = bar
        self.baz = baz


def foo():
    data = {"bar": "bar", "baz": 1}
    return Foo(**data)


if __name__ == "__main__":
    foo()
```


Calling:
```sh
RUST_BACKTRACE=1 pylyzer 1.py
Start checking: 1.py
thread 'pylyzer' panicked at 'called `Option::unwrap()` on a `None` value', crates/py2erg/convert.rs:1057:40
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: py2erg::convert::ASTConverter::convert_expr::{{closure}}
   4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   5: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   6: py2erg::convert::ASTConverter::convert_expr
   7: py2erg::convert::ASTConverter::convert_statement
   8: py2erg::convert::ASTConverter::convert_block
   9: py2erg::convert::ASTConverter::convert_statement
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  11: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  12: py2erg::convert::ASTConverter::convert_program
  13: pylyzer::analyze::PythonAnalyzer::analyze
  14: pylyzer::analyze::PythonAnalyzer::run
  15: pylyzer::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Thread panicked: Any { .. }
```

**Comment by arminveres** [comment]
Same here, it doesn't start on empty files and crashes on any other that has some form of code in it.

**Comment by mtshiba** [comment]
Fixed in the latest version.
