### ISSUE TITLE
VSCode extension: Client pylyzer: connection to server is erroring. Shutting down server.

### ISSUE THREAD

**Issue by KirillY** [mtshiba/pylyzer#70]
Cannot use extention 
```text
[Error - 12:57:04 AM] Client pylyzer: connection to server is erroring. Shutting down server.
[Error - 12:57:04 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at b.shutdown (/home/username/.vscode-server/extensions/pylyzer.pylyzer-0.1.7/dist/extension.js:1:104625)
	at b.stop (/home/username/.vscode-server/extensions/pylyzer.pylyzer-0.1.7/dist/extension.js:1:104206)
	at b.stop (/home/username/.vscode-server/extensions/pylyzer.pylyzer-0.1.7/dist/extension.js:1:266220)
	at b.handleConnectionError (/home/username/.vscode-server/extensions/pylyzer.pylyzer-0.1.7/dist/extension.js:1:110713)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[91m[ERR] ERG_PATH not found[m
[Error - 12:57:09 AM] Client pylyzer: connection to server is erroring. Shutting down server.
[Error - 12:57:09 AM] Stopping server failed
...
Error: Client is not running and can't be stopped. It's current state is: starting
	at b.shutdown (/home/username/.vscode-server/extensions/pylyzer.pylyzer-0.1.7/dist/extension.js:1:104625)
	at b.stop (/home/username/.vscode-server/extensions/pylyzer.pylyzer-0.1.7/dist/extension.js:1:104206)
	at b.stop (/home/username/.vscode-server/extensions/pylyzer.pylyzer-0.1.7/dist/extension.js:1:266220)
	at b.handleConnectionError (/home/username/.vscode-server/extensions/pylyzer.pylyzer-0.1.7/dist/extension.js:1:110713)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by KirillY** [comment]
Resolved by disabling then enabling extention
