### ISSUE TITLE
Broken on Windows

### ISSUE THREAD

**Issue by ArneBachmannDLR** [mtshiba/pylyzer#8]
After `pip install pylyzer` there seems to be a dependency on an installed cargo build environment or such:

```bash
thread '<unnamed>' panicked at 'ERG_PATH not found: Os { code: 3, kind: NotFound, message: "Das System kann den angegebenen Pfad nicht finden." }', C:\Users\sbym8\.cargo\registry\src\github.com-1ecc6299db9ec823\erg_common-0.6.7-nightly.2\env.rs:10:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', C:\Users\sbym8\.cargo\registry\src\github.com-1ecc6299db9ec823\erg_common-0.6.7-nightly.2\spawn.rs:31:22
```

**Comment by ArneBachmannDLR** [comment]
Well that was too easy, my bad.

Hint: pylyzer writes color codes as escape codes, which does not work in the cmd.exe shell, but works in the new Terminal app; you could probably integrate colorama or a similar library for that. I could not test color output on the the Git bash and Powershell, as I cannot activate conda environments in those.
