### ISSUE TITLE
VSCode plugin crash

### ISSUE THREAD

**Issue by sircambridge** [mtshiba/pylyzer#88]
I installed pylyzer via "pip install pylyzer" per the vscode extension instructions, but I keep getting this in the output:

did I install it incorrectly?

true
thread 'pylyzer' panicked at 'called `Option::unwrap()` on a `None` value', crates/py2erg/convert.rs:1057:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Thread panicked: Any { .. }
[Info  - 4:16:25 PM] Connection to server got closed. Server will restart.
true
thread 'pylyzer' panicked at 'called `Option::unwrap()` on a `None` value', crates/py2erg/convert.rs:1057:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Thread panicked: Any { .. }
[Error - 4:16:26 PM] The pylyzer server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

**Comment by mat-ej** [comment]
I am having similar issues, I can run pylyzer from cli but with the extension it does not seem to run 

```
Pending response rejected since connection got disposed

 Client is not running and can't be stopped. It's current state is: starting
```

**Comment by mat-ej** [comment]
literally over...
